// Generated by gencpp from file plumbing_server_client/Serial.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_SERIAL_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_SERIAL_H

#include <ros/service_traits.h>


#include <plumbing_server_client/SerialRequest.h>
#include <plumbing_server_client/SerialResponse.h>


namespace plumbing_server_client
{

struct Serial
{

typedef SerialRequest Request;
typedef SerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Serial
} // namespace plumbing_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_server_client::Serial > {
  static const char* value()
  {
    return "a706874ecb124873b6727a0a5b02b832";
  }

  static const char* value(const ::plumbing_server_client::Serial&) { return value(); }
};

template<>
struct DataType< ::plumbing_server_client::Serial > {
  static const char* value()
  {
    return "plumbing_server_client/Serial";
  }

  static const char* value(const ::plumbing_server_client::Serial&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_server_client::SerialRequest> should match
// service_traits::MD5Sum< ::plumbing_server_client::Serial >
template<>
struct MD5Sum< ::plumbing_server_client::SerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::Serial >::value();
  }
  static const char* value(const ::plumbing_server_client::SerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::SerialRequest> should match
// service_traits::DataType< ::plumbing_server_client::Serial >
template<>
struct DataType< ::plumbing_server_client::SerialRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::Serial >::value();
  }
  static const char* value(const ::plumbing_server_client::SerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_server_client::SerialResponse> should match
// service_traits::MD5Sum< ::plumbing_server_client::Serial >
template<>
struct MD5Sum< ::plumbing_server_client::SerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::Serial >::value();
  }
  static const char* value(const ::plumbing_server_client::SerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::SerialResponse> should match
// service_traits::DataType< ::plumbing_server_client::Serial >
template<>
struct DataType< ::plumbing_server_client::SerialResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::Serial >::value();
  }
  static const char* value(const ::plumbing_server_client::SerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_SERIAL_H
