// Generated by gencpp from file plumbing_server_client/SerialRequest.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_SERIALREQUEST_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_SERIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plumbing_server_client
{
template <class ContainerAllocator>
struct SerialRequest_
{
  typedef SerialRequest_<ContainerAllocator> Type;

  SerialRequest_()
    : InputData()  {
    }
  SerialRequest_(const ContainerAllocator& _alloc)
    : InputData(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _InputData_type;
  _InputData_type InputData;





  typedef boost::shared_ptr< ::plumbing_server_client::SerialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plumbing_server_client::SerialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialRequest_

typedef ::plumbing_server_client::SerialRequest_<std::allocator<void> > SerialRequest;

typedef boost::shared_ptr< ::plumbing_server_client::SerialRequest > SerialRequestPtr;
typedef boost::shared_ptr< ::plumbing_server_client::SerialRequest const> SerialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plumbing_server_client::SerialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plumbing_server_client::SerialRequest_<ContainerAllocator1> & lhs, const ::plumbing_server_client::SerialRequest_<ContainerAllocator2> & rhs)
{
  return lhs.InputData == rhs.InputData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plumbing_server_client::SerialRequest_<ContainerAllocator1> & lhs, const ::plumbing_server_client::SerialRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plumbing_server_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_server_client::SerialRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plumbing_server_client::SerialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_server_client::SerialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e89ba793d64173265bf57d3300c00a82";
  }

  static const char* value(const ::plumbing_server_client::SerialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe89ba793d6417326ULL;
  static const uint64_t static_value2 = 0x5bf57d3300c00a82ULL;
};

template<class ContainerAllocator>
struct DataType< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plumbing_server_client/SerialRequest";
  }

  static const char* value(const ::plumbing_server_client::SerialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] InputData\n"
;
  }

  static const char* value(const ::plumbing_server_client::SerialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.InputData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plumbing_server_client::SerialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plumbing_server_client::SerialRequest_<ContainerAllocator>& v)
  {
    s << indent << "InputData[]" << std::endl;
    for (size_t i = 0; i < v.InputData.size(); ++i)
    {
      s << indent << "  InputData[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.InputData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_SERIALREQUEST_H
